flask_shop/models.py
from flask.ext.login import UserMixin
from flask_shop import bcrypt, app
from flask.ext.sqlalchemy import SQLAlchemy

db = SQLAlchemy(app)


products = db.Table('products',
    db.Column('product_id', db.Integer, db.ForeignKey('product.id')),
    db.Column('order_id', db.Integer, db.ForeignKey('order.id'))
)

class Product(db.Model):
    __tablename__ = 'product'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, unique=True)
    description = db.Column(db.String)
    image = db.Column(db.String)
    price = db.Column(db.Float, default=0.0)
    discontinued = db.Column(db.Boolean, default=False)

    def __unicode__(self):
        return self.name


class Order(db.Model):
    __tablename__ = 'order'
    id = db.Column(db.Integer, primary_key=True)
    uuid = db.Column(db.String)
    stripe_id = db.Column(db.String)
    client_email = db.Column(db.String)
    total_price = db.Column(db.String)
    description = db.Column(db.String)
    products = db.relationship('Product', secondary=products,
        backref=db.backref('orders', lazy='dynamic'))
    completed = db.Column(db.Boolean, default=False)
    completed_by = db.Column(db.Integer, db.ForeignKey('user.id'))
    comment = db.Column(db.String)
    created = db.Column(db.DateTime)

    def __unicode__(self):
        return '%s - %s' %  (uuid, client_email)


class User(db.Model, UserMixin):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String)
    password = db.Column(db.String)
    active = db.Column(db.Boolean, default=True)
    created = db.Column(db.DateTime)
    updated = db.Column(db.DateTime)

    def set_password(self, password):
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, password):
        return bcrypt.check_password_hash(self.passwords, password)

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return unicode(self.id)

    def __repr__(self):
        return self.email

    def is_admin(self):
        return False

    def __str__(self):
        return self.email

flask_shop/forms.py
from flask.ext.wtf import Form
from wtforms import PasswordField
from flask.ext.wtf.html5 import EmailField
from wtforms.validators import Required


class LoginForm(Form):
    email = EmailField('email', [Required()])
    password = PasswordField('Password', [Required()])

flask_shop/__init__.py
"""
Flask-Shop description here.

"""

__version_info__ = ('0', '0', '1')
__version__ = '.'.join(__version_info__)
__author__ = 'Burak Demirtas'
__license__ = 'BSD'
__copyright__ = '(c) 2014 by Burak Demirtas'

flask_shop/views.py
from flask.ext.login import LoginManager, login_required, login_user, logout_user, current_user
from flask import flash, redirect, url_for, session, render_template, request, Blueprint
from flask_shop import app
from .forms import LoginForm
from .models import User, Product, Order
login_manager = LoginManager(app)
flask_shop = Blueprint('shop', __name__, url_prefix='/shop')


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


@flask_shop.route('/')
def index():
    # products = Product.query.filter_by(discontinued=False).all()
    products = Product.query.all()
    return render_template('shop.html', products=products)

@flask_shop.route('/product', methods=['GET']) # Retrive all products
@flask_shop.route('/product', methods=['POST']) # Add new product
@flask_shop.route('/product/<id>', methods=['GET']) # Retrive one product by id
@flask_shop.route('/product/<id>', methods=['PUT']) # Update product by id
@flask_shop.route('/product/<id>', methods=['DELETE']) # Delete product by id
def product(id=None):
    if request.method=='GET':
        products = Product.objects.all()
        return 'GET'
    if request.method=='POST':
        return 'POST'
    if request.method=='PUT':
        return 'PUT'
    if request.method=='DELETE':
        return 'DELETE'
    return 'Product Admin page', 200


@flask_shop.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@flask_shop.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated():
        return redirect(url_for('shop.reports'))
        redirect()
    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects.get_or_404(email=form.email.data)
        if user is not None and user.check_password(form.password.data):
            flash(u'Successfully logged in as %s' % user.email)
        session['user_id'] = user.id
        login_user(user)
        return redirect(url_for("shop.reports"))
    return render_template('login.html', form=form)


# @flask_shop.route("shop")
# def shop():
#     products = Product.query.filter(discontinued=False).all()
#     render_template('shop', products=products)


@flask_shop.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('shop.login'))


@flask_shop.route('/reports', methods=['POST'])
@login_required
def reports():
    pass


@flask_shop.route('/charge', methods=['POST'])
def charge():
    pass

flask_shop/templates/base.html
<html ng-app="shopApp">
<head>
  <title>Flask-Shop</title>
  <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script> 
  <script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.shorten.js') }}"></script>

  <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/bootstrap.css') }}">
  <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/bootstrap-theme.css') }}">
  <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/styles.css') }}">
  {% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
</head>
<body ng-controller="CartController">
{% if current_user.is_authenticated()%}
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container-fluid">
			<div class="btn-toolbar pull-right" style="margin:0px;">
				<div class="btn-group">
				</div>
				<div class="btn-group">
					<a class="btn btn-info dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="icon-cog"></i> 
						{{current_user.username}}
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu pull-right">
						<li><a href="{{ url_for('shop.logout') }}">Logout</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
{% endif %}
<div id="content" class="container-fluid">
{% block content %}
{% endblock %}
</div>
<script src="{{ url_for('static', filename='js/cart.js') }}"></script>
<script src="{{ url_for('static', filename='js/angular.min.js') }}"></script>
</body>
</html>

flask_shop/templates/charge.html
{% extends "layout.html" %}
{% block content %}
{% endblock %}

flask_shop/templates/index.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

flask_shop/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="login-container" style="margin: 0 auto;text-align: center;">
	<form class=form-horizontal action="{{ url_for('shop.login') }}" method=post>
	  {{ form.hidden_tag() }}
	  {{ form.email(placeholder='Email') }}
	  <br/>
	  {{ form.password(placeholder='Password') }}
	  <div class=control-group>
	    <div class=controls>
	      <button type=submit class="btn btn-primary">Login</button>
	    </div>
	  </div>
	</form>
</div>
{% endblock %}

flask_shop/templates/shop.html
{% extends "base.html" %}
{% block content %}
<div class="row">
	<div class="col-md-7">
	{% for product in products %}
	<div class="col-md-12">
		<div id="{{product.name}}" class="thumbnail">
		  <img src="{{product.image}}" alt="">
		  <form ng-submit="addItem()">
			 <h3 class="item_name">{{product.name}}</h3>
			 <span>Description: </span><div class="item_description">{{product.description}}</div>
			 <span>Quantity: </span><input value="1" class="item_quantity" type="text"><br>
			 <span>Price: </span><span class="item_price">{{product.price}}</span><br>
			 <button type="submit" value="Add to Cart" class="btn btn-primary btn-xs" id="submit">Add to Cart</button>
		   </form>
  		</div>
	</div>
	{% endfor %}
	</div>
	<div class="col-md-5">
	<div class=" cart_container">
		<div class="cart">
			<h2>Cart</h2>
			<ul class="items" id="items">
				<li class="item" ng-repeat="item in cart">
					<div>Title: {{item.title|angular}}</div>
					<div>Price: {{item.price|angular}}</div>
					<span ng-model="quantity">Quantity: {{item.quantity|angular}}</span>
					<div>Total price: {{item.total_qty|angular}}</div>
					<button class="btn btn-primary btn-xs" ng-click="removeItem($index)">Remove</button>
				</li>
			</ul>
			<div class="cartTotal">
			</div>
		</div>
	</div>
	</div>
</div>
{% endblock %}

flask_shop/templates/stripe.html
{% extends "layout.html" %}
{% block content %}
{% endblock %}